[[intro]]

== Introduction

This document describes a holistic solution for securely partitioning workloads
on RISC-V-based platforms, based on (and by enhancing);

* WorldGuard, per the publicly-available v0.4 specification
* TrustZone(R) interoperability, assuming AXI signalling
* ePMP, per the RISC-V privileged specification
* IOPMP, per the v0.7 specification footnote:[Please note that IOPMP changed
  version numbering when it was previously at or around version "0.9.2-RC3". As
  of début March 2025, v0.7 is the current release.]

This solution was arrived at by MIPS as part of its security architecture
development and it is hoped that it might provide a general solution for the
RISC-V ecosystem, hence the contribution of this document.

The goals of this document are;

* to describe how these technologies can be adapted to work together in a
  complementary manner,
* to permit review and refinement by RISC-V stakeholders, and
* to facilitate the integration of enhancements into their respective upstream
  projects in a coordinated fashion.

