[[intro]]

== Introduction

This document describes a holistic solution for securely partitioning workloads
on RISC-V-based platforms, based on (and by enhancing);

* RISC-V "Worlds", per the link:https://github.com/riscv/riscv-worlds[draft specification]
* TrustZone(R) interoperability, assuming AXI signalling
* ePMP, per the RISC-V privileged specification
* IOPMP, per the link:https://github.com/riscv-non-isa/riscv-iopmp/releases/tag/v0.8.2[v0.8.2 specification]

This solution was initially developed by MIPS and is now being developed in
collaboration with other members of the RISC-V community. It is hoped that it
might provide some useful input to the development of RISC-V standards and
approaches.

The goals of this document are;

* to describe how these technologies can be adapted to work together in a
  complementary manner,
* to permit review and refinement by RISC-V stakeholders, and
* to propose and facilitate the contribution of various enhancements into their
  respective upstream projects/specifications.

