:imagesdir: ./images

[[overview]]
== Architecture Overview

=== Reconciling technologies

This document attempts to present (and demonstate how to reconcile) the
following complementary partitioning concepts:

* Worlds, a new concept that owes its heritage to the WorldGuard definition
  released by SiFive.
* NS-Req security levels and NS-Attr security attributes, concepts drawn from
  the "Secure/Non-Secure" model popularized by TEEs (Trusted Execution
  Environments) and implemented by ARM(R) TrustZone(R).
* Physical Memory Protection, hereafter "PMP";
** "ePMP" for processor-initiated transactions
** "IOPMP" for device-initiated transactions

TrustZone(R) is a security technology developed by ARM(R) for their processor
families that creates an asymmetric division of a system into two isolated
resource domains, one "Secure" and the other "Non-Secure". This can be thought of as
a composition of two functionalities;

* A symmetric isolation capability for two worlds.
* An asymmetric assignment of security levels ("Secure" and "Non-Secure") to
  those two worlds, and the behavioral distinctions between those two security
  levels.

"Worlds" is a generalization of the symmetric isolation concept (from two to
`NWorlds` worlds), and "Security Levels" is a generalization of the asymmetric
security level concept (from two to `NLevels` security levels).

There are multiple reasons to want to harmonize these partitioning concepts,
among them;

* Worlds, NS-Req security levels and NS-Attr security attributes conveniently
  map to the ARM(R) TrustZone(R) model, allowing for interoperation and
  integration with TrustZone(R)-centric technology.
* The TrustZone(R) approach has been underpinning Trusted Execution Environment
  (TEE)-style solutions for many years, so this facilitates the porting of TEE
  solutions to RISC-V.
* There is industry demand to be able to create RISC-V/ARM(R) hybrid solutions,
  e.g. by embedding RISC-V cores into ARM(R)/TrustZone(R)-centric SoCs (and
  vice versa).

The following subsections provide background information about each of these
technologies and hint at how they will be adapted to work together.

=== TrustZone(R)

AMBA protocols define a boolean security attribute (`AxPROT[1]` in AXI) that
can be checked and interpreted at (or on route to) the transaction's target,
giving rise to the concept of "Secure" (versus "Non-Secure") transactions. This
is sometimes called the "NS bit".

ARMv8-M uses the term "NS-Req" to refer to the TZ security level of a request,
and "NS-Attr" to refer to the TZ security attribute of an addressable resource
that an NS-Req can be compared against.

=== Worlds

Worlds is a RISC-V-native approach to system-partitioning, in which initiators
implement "marker" functionality to control the tagging of outgoing
transactions with appropriate "World ID" (hereafter "WID") values, and bus
gaskets and target devices implement "checker" functionality to perform
WID-aware processing at (or on route to) the transaction's target.

This gives rise to the concept of software and other transaction-emitting
resources being separated into "Worlds" that have distinct levels of access to
addressable resources within the system.

"Worlds" does not innately have any specific concept for "Secure" or
"Non-Secure" transactions or partitions. The assumption is that the Worlds
concept is used to obtain a desired partitioning arrangement, without
consideration to which worlds' workloads are more (or less) "secure" than any
others.

The World-ID ISA uses per-hart CSR registers, including the control that locks
M-mode limitations into place until the next reset. These would typically be
initialized as part of a secure-boot process and so may be driven by an
external processing element (such as a discrete HSM block). __We will clarify
how the Worlds definition should be exposed for external configuration.__

The ISA implementation has a corresponding, and software-discoverable,
`NWorlds` configuration constant, representing the maximum number of distinct
Worlds supported by the ISA functionality.

[[introNSReq]]
=== NS-Req security levels

NS-Req is a single-bit scale that the system can assign to Worlds in order to
define a security stratification. The value zero corresponds to "Secure" and
the value 1 corresponds to "Non-Secure", which is where the "NS" acronym
originates. When the core initiates a load/store/fetch transaction, this
security level can be signalled on the outgoing request, which is where the
"Req" originates.

There is a further extension available for the hart to enforce/police the
expected NS-Req relationships between the hart's privilege levels. This ensures
that the NS-Req for S-mode is never superior to the NS-Req for M-mode, that
U-mode is never superior to S-mode, etc.

[[introNSAttr]]
=== NS-Attr security attributes

NS-Attr security attributes are assigned to accessible resources (address
ranges) as a form of access-control. The NS-Req of a transaction request can be
compared against the NS-Attr of the targetted resource in order to determine
whether the access should go ahead. This is usually performed as a source-check,
meaning that the decision point controls whether or not a transaction request
should be emitted.

The NS-Attr security attribute encodes;

* whether access should be granted for a Non-Secure NS-Req,
* if access is granted, whether the transaction should be signalled as Secure
  or Non-Secure.

The encoding can cause a Secure NS-Req to emit a Non-Secure transaction, but
does not allow a Non-Secure NS-Req to emit a a Secure transaction (to inhibit
privilege-escalation).

One subtlety to note about NS-Attr is with respect to instruction fetching and,
if an MMU is present, page-table fetches. A Secure workload shouldn't fetch
instructions (nor should it load page-tables) from an address range that might
be accessible to a Non-Secure workload, to close the attack vectors that could
otherwise result. As such, for those classes of transaction, the comparison
between NS-Req (the state of the hart) and the NS-Attr (the resource) is
constrained, i.e. "Secure" worlds can only fetch (or load page-tables) from
"Secure Memory".

=== ePMP

ePMP is the per-hart mechanism used by RISC-V cores to partition the physical
address space with privilege-based access controls. These control access to
physical address ranges based on the active privilege mode of the hart and the
attempted access type. As with the other partitioning mechanisms, it naturally
lends itself to having "lockable" configuration, to constrain M-mode access in
a way that it can't subsequently reconfigure (without a reset).

There is no need to adjust ePMP for WID isolation behavior, but there is a need
to enhance it to support NS-Attr-enforcement behavior.  __Specifically, ePMP
will need to be cognizant of (i) the hart's effective NS-Req security level,
and (ii) the target resource's NS-Attr, in order to prevent the hart from
accessing a resource that it shouldn't. ePMP may also be responsible for
recording (through `pmpnsX` register settings) the NS-Attr attributes of
physical address ranges, depending on how the platform manages such attributes
(and on whether the Smwidnsreg extension is enabled).__

=== IOPMP

The publicly-defined IOPMP block is independent of the WID, NS-Req, and NS-Attr
(and TrustZone(R)) concepts. It specifies a prototypical "checker" (with
minimal "marker" functionality also) for use with device initiators. This
configurable block is a form of firewall and is proposed primarily for the
purpose of providing source-side transaction checking for a device, akin to the
source-side checking provided by ePMP for core-initiated transactions. The
IOPMP definition also suggests that IOPMP might be used target-side, but leaves
as "implementation-dependent" the manner in which an input RRID would be
provided in that case.

To make use of WID (at all) and/or NS-Req (outside the hart), there must be
WID-aware (and/or NS-Req-aware) targets and/or routers within the interconnect,
otherwise there is little point to tagging transactions with either concept.
__We achieve this by making a small series of improvements to IOPMP.__ The
resulting "enhanced IOPMP" (hereafter "eIOPMP") can be instantiated as a
target-side or routing firewall.

Note also that, as with ePMP, there is the implementation-specific decision of
how the NS-Attr attributes are maintained for the physical address space, so
that the eIOPMP can compare the NS-Req of the request(er) against the target
range. __We provide an optional mechanism for recording the NS-Attr attributes
of physical address ranges within the ePMP/eIOPMP configuration.__

[[extconfig]]
=== External configuration

In many cases RISC-V cores are represented as a subsystem that is placed into a
host SoC, and in such use-cases it is often desirable to be able to configure
the security framework of that subsystem during a secure-boot phase, prior to
the subsystem executing any workload. It can also happen later on that the
subsystem is reset, perhaps with the requirement to reinitialize. In both
cases, we can see that there is a Root of Trust (hereafter "RoT") that is
"external" to the subsystem that should be able to impose its chosen security
configuration on the subsystem.

In all such cases we assume:

* There is a means to expose a selected subset of per-hart CSRs and per-device
  registers to the external environment for partitioning control.
* This external control may be blocked (or become read-only) when the
  cores/harts/devices they control are executing/enabled. (This assumption can
  simplify implementation and verification.)
* If there is value to making a setting available for external control, it
  follows that the control in question should be "lockable", such that settings
  become immutable before the affected harts execute (and/or the affected
  devices are enabled). The converse is true also: if a configuration is
  lockable, it makes sense for it to be configurable by external control.
* External configuration may be optional, in that the subsystem harts may
  perform their own self-configuration.
** Alternatively, for implementations intended to always be externally
   configured, these configuration registers may always be read-only to the
   harts.

==== World-ID

As we will see later, the World-ID registers divide logically into two groups,
_"Lockable partitioning registers"_, and _"Run-time manipulable registers"_.

__It is the former, the so-called lockable partitioning registers, that should
be exposed for external control.__

==== ePMP

ePMP also contributes to the system partitioning, through the ability to write
(and lock) rules that govern even M-mode's access to the hart's addressable
resources. On some platforms (when Smwidnsreg is enabled), the `pmpnsX`
registers may also be the way in which physical address ranges are assigned
their SQ attributes. __The ePMP registers should be exposed for external
control.__

==== eIOPMP

eIOPMP is, at its core, a look-aside firewall component with a set of
configuration registers. It may also be packaged as a bus gasket, which may add
to the configuration interface (otherwise the look-aside is presumably embedded
within another component and its register map)footnote:[There are interconnects
that can incorporate look-aside components of this sort. Or it may be
integrated into an IOMMU, DMA engine, memory controller, ...]. It is an
integration-level decision where an eIOPMP instance's registers appear and how
they are exposed.

As with the ePMP, the eIOPMP may also be responsible for recording the SQ
attributes for the physical address ranges it covers, this depends on how the
platform chooses to implement these attributes. (They may alternatively be
tracked by the platform's PMAs, i.e. Physical Memory Attributes, in which case
the eIOPMP may instead obtain the information that way.) __The eIOPMP may be
responsible for recording the NS-Attr attributes of the physical address ranges
it covers.__

Though some of the IOPMP register settings advertise their own locking
mechanisms, they only provide for a partial lockdown of the
partitioning-relevant configuration. In this specification, __we provide an
additional lock field that locks down the eIOPMP configuration interface as a
whole (with the exception of the "Error capture registers").__

__The whole eIOPMP configuration interface should be exposed for external
control.__

[[rotMode]]
==== RoT-mode and M-mode

We have argued that the ability to perform lockable configuration from outside
the (sub)system should be equivalent to the ability to perform lockable
configuration from M-mode within the (sub)system. If we ignore any distinction
between the two and consider them as the same logical entity - then we could
note that this entity has the privilege to set lockable configuration, after
which the configuration cannot be altered by run-time M-mode, which is
constrained by its effects. If one considers that observation, one can talk
about a metaphorical "RoT-mode" that is more highly privileged than "run-time
M-mode", because the former can configure constraints on the latter.

This ostensible "RoT-mode" concept is usefully vague, it applies equally to
early-boot M-mode code and/or to a completely external agent. But that has
value in itself, as that is the comparison between (a) a system that boots
itself, with (b) a subsystem that is booted by a parent system.  As we will see
in the diagrams of <<extensions>>, the addition of this "RoT-mode" psuedo
privilege level allows a constraints-based visualization to emerge, which
extends from U-mode through M-mode to beyond-the-hart. Constraining M-mode is
the desired side-effect.

The lockable configuration that would be controlled by RoT-mode includes;

* ePMP locked configuration (CSRs)
* World-ID "lockable partitioning registers" (CSRs)
* System-level IOPMP instances (device-mapped registers)

=== Extensions and documentation grouping

In keeping with RVI convention, functionality is introduced in small units
known as extensions, often at a fine-grain granularity. The assumption is that
these extensions will typically be employed in coarser-grained groupings, and
that profiles may be defined to this effect also.

This document will divide itself into coarse-grain "sub-proposal" sections,
such that each can provide its own context, requirements, and solutions in as
separable a manner as possible.

* "Worlds" baseline
** The "World-ID" ISA extension set. This is derived from the original
   WorldGuard v0.4 proposal from SiFive by making some tweaks and adding
   support for the Hypervisor extension. It provides support for World-based
   marking of core-initiated transactions.
** The "eIOPMP extension". This is derived from v0.7 of the draft IOPMP
   specification by making some tweaks and clarifications, and adding support
   for match-based output WID/RRID. I.e. an eIOPMP that can map from an input
   WID namespace to an output WID namespace.
* NS-Req
** The "NS-Req" ISA extension set. This allows World IDs to be classified by
   security level. It also enforces sane relationships between the security
   levels of the hart's 3 privilege levels.
** The "eIOPMP NS-Req" non-ISA extension. This is to the eIOPMP what the
   "NS-Req" ISA extension set is to the hart, it classifies the available
   World IDs into their respective NS-Req security levels, which is useful if
   the eIOPMP instance is configured to signal the resulting NS-Req on outgoing
   transactions.
* NS-Attr
** The "NS-Attr" ISA extension. This extension defines the concept a security
   attribute that one associates with a resource's physical address range. The
   hart checks all outgoing load/store/fetch transactions using the effective
   WID's NS-Req and, by comparing that against the NS-Attr for the target
   physical address, it faults any transactions that aren't permitted. This
   extension assumes the platform has a mechanism for defining NS-Attr
   attributes for the accessible address space, e.g. as a PMA (Physical Memory
   Attribute).
** The "eIOPMP NS-Attr" non-ISA extension. This is to the eIOPMP what the
   "NS-Attr" extension is to the hart, it introduces the NS-Attr concept to the
   eIOPMP, implying that it will perform enforcement of NS-Attr on all input
   transactions before forwarding (or rejecting) them.
* PMP registration of NS-Attr attributes.
** The "ePMP NS-Attr registry" ISA extension. This extension advertises that
   the ePMP manages the NS-Attr attributes for the hart's accessible physical
   address space, as an alternative to any other platform-specific mechanism
   for recording attributes.
** The "eIOPMP NS-Attr registry" non-ISA extension. This is to the eIOPMP what
   the "ePMP NS-Attr registry" extension is to the hart, it advertises that the
   eIOPMP manages the NS-Attr attributes for the eIOPMP's accessible physical
   address space, as an alternative to any other platform-specific mechanism
   for recording attributes.

Here is an overview of the ISA extensions covered in this document;

[%header,cols="3,1,3"]
|===
| *Sub-proposal* | *Ext name* | *Content*
.5+| World-ID baseline | Smwid | Hart-specific WID
                       | Smwidl | Lower-than-M-mode WID
                       | Smwidm | Delegation to M-mode
                       | Smwids | User-mode and delegation to S-mode
                       | Smwidv | Hypervisor support
.2+| NS-Req            | Smwidns | NS-Req assignments and signalling
                       | Smwidnsc | NS-Req privilege constraints
| NS-Attr              | Smwidnsa | NS-Attr transaction checking
| PMP registration of NS-Attr | Smwidnsreg | ePMP registration of NS-Attr
|===

