:imagesdir: ./images

[[isa]]
== "World-ID" ISA extension set

=== Preamble

The original WG solution proposes a sequence of incremental extensions that
progressively add CSR registers but do not add any new instructions. We propose
that;

* All the WG extensions are supported and permanently enabled.
** The complexity of the first WG extension is close enough to the complexity
   of incorporating them all that we find little benefit to implementing
   intermediary levels, even in microcontroller form-factors. Not having to
   support such intermediary levels also provides a welcome simplification.
** It is reasonable to have WG permanently enabled because default settings can
   be obtained that provide behavior functionally equivalent to WG being
   disabled.
* The publicly-available WG definition is modified;
** For improvement of WG;
*** Addition of `mwid` and `mwidlist` CSRs and their respective
    behaviors.footnote:[There is a second publicly-available WG document that
    suggests the existence of these two additional CSRs, but it does not
    specify any detail so we are treating our definition as a modification.]
*** World ID (or `WID`) registers are reduced to a theoretical maximum of 16
    bits, for consistency with IOPMP's `RRID` and to leave register space for
    future extensions.
*** Alternative illegal-value (and WARL) semantics for the WG CSRs.
** Sane power-on defaults that behave as a system without any partitioning.
** To support the Hypervisor extension, addition of `hlwid`, `hwiddeleg`,
   `vslwid` and associated behaviors.
* Some of the WG CSRs be exposed for external control.

[[nonHypervisorTree]]
=== Non-hypervisor decision tree

The following diagram captures the World-ID decision tree (for core-emitted
load/store/fetch transactions), without any support for the privilege modes
introduced by the Hypervisor extension. Please note that the nested checking,
whereby a `mwiddeleg` check is followed by a `mwidlist` check, is the reason
that we don't have to insist that `mwiddeleg` be a subset of `mwidlist`, and
the reason why we can avoid "illegal value" semantics.

[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="World-ID non-Hypervisor decision tree"]
image::WG-V0.drawio.svg[]

[[hypervisor]]
=== Hypervisor support

The addition of the Hypervisor extension adds a boolean `V` mode that affects
the behavior of `S` and `U` modes. When `V=0`, `S` and `U` mode are referred to
as `HS` and `HU` respectively (here `H` represents "Host" or "Hypervisor",
either will do). When `V=1`, they are referred to as `VS` and `VU`
respectively. (`V` represents "Virtual".) When the Hypervisor extension is
enabled, the behavior defined in <<nonHypervisorTree>> for `S` and `U` is also
the expected behavior for the `V=0` case, i.e. for `HS` and `HU`.

What remains is to define the expected behavior for the `VS` and `VU` states,
which we do via the addition of two `HS`-level registers (that are not visible
to `VS`), called `hlwid` and `hwiddeleg`, and a single `VS`-level shadow
register called `vslwid`. These extend the existing WID and WID-delegation
concepts to the additional level of privilege hierarchy that the H extension
introduces.

The following diagram extends the previous one to illustrate the World-ID
decision tree when the Hypervisor extension is enabled;

[[hypervisorWGtree]]
[caption="Figure {counter:image}: ", reftext="Figure {image}"]
[title="World-ID Hypervisor-extended decision tree"]
image::WG-V1.drawio.svg[]

=== Configuration handling

The precise behavior of (and interaction between) the CSRs will be described in
two parts, depending on whether they are the _lockable partitioning registers_
(`mwid`, `mwidlist`, `mwidseclist`) or the _run-time manipulable registers_
(`mlwid`, `mwiddeleg`, `hlwid`, `hwiddeleg`, `slwid`, `vslwid`). They are in
sections <<lockablePartitioning>> and <<runtimeManipulable>>, respectively.

==== Illegal values

For registers holding WID values, the most recent publicly-available WG
proposal stipulates: "if an illegal WID is written, the lowest-numbered legal
WID is returned". It does not specify how WID-holding registers should behave
if, rather than them being written with illegal values, __their existing values
become implicitly illegal__ due to changes to other registers.

In this proposal, we opt for different semantics to handle such cases and
therefore deviate from the original WG proposal. Instead of having "illegal
values" that need to be corrected (in a WARL sense), we allow all registers to
assume arbitrary values, whereby the so-called "illegal values" simply
correspond to (mis)configurations that by their nature will fail to operate.
(The only corrective WARL behavior required is to limit the number of supported
bits.)

==== Register visibility

This proposal takes a minimalist approach to register visibility. Specifically,
World-ID registers are only visible to privilege levels that have writable
control over them. If a software context needs to know any WID or WID-bitmask
values that it does not have control over (e.g. S-mode software wanting to know
`mwiddeleg`, which indicates the set of WIDs delegated to it), then that will
need to be conveyed to it through software mechanisms.

[[lockablePartitioning]]
==== Lockable partitioning registers

`mwid`, `mwidlist`

* These are the CSR registers that are exposed for external configuration
  control.
* These registers are assumed to be set statically to constrain the hart until
  it is next reset, and the behavior of the "run-time manipulable registers" is
  governed by these registers.
* Apart from the "L"ock bit in `mwid` (which is sticky to 1 and renders both
  registers read-only until the next reset), these registers are modifiable
  independently and no combination of values is illegal, _per se_.
* These partitioning registers place no constraints on the order in which
  they're read or written. (This simplifies the hardware design and resulting
  programming model.)

[[runtimeManipulable]]
==== Run-time manipulable registers

`mlwid`, `mwiddeleg`, `hlwid`, `hwiddeleg`, `slwid`, `vslwid`

* These are the CSRs that are expected to be modified by M-mode and S-mode at
  run-time, though many use-cases will use static/unchanging values for these
  CSRs also. These CSRs are not lockable and are not exported for external
  configuration, and so they are not considered part of the partitioning
  configuration (rather, they work within the partitioning configuration).
* `mlwid`: this register determines the effective WID of (H)S-mode. Though it
  makes sense for the corresponding bit in `mwidlist` to be set, there is no
  need to enforce such relationships at the register level, the catastrophic
  effects of this kind of misconfiguration will take care of matters. (Loads,
  stores, and instruction fetches will be blocked for S-mode.)
* `hlwid`: this register determines the effective WID of VS-mode. It makes sense
  for the corresponding bits in `mwidlist` and `mwiddeleg` to be set, but there
  is no need to enforce such a relationship at the register level.
* `slwid`: this register determines the effective WID of U-mode. It makes sense
  for the corresponding bits to be set in `mwidlist` and `mwiddeleg`, but there
  is no need to enforce such relationships at the register level.
* `vslwid`: This CSR is the virtualization shadow register of the slwid
   register. In HS-mode this register can be programmed to set the effective WID
   of VU mode. It makes sense for the corresponding bits in `hwiddeleg` to be
   set, but there is no need to enforce such a relationship at the register
   level.
* `mwiddeleg`: this register determines the WIDs that (H)S-mode is allowed to
  assign to U-mode (and, if the Hypervisor extension is enabled, VS-mode), i.e.
  those WIDs that can (or should) be set in `slwid` (and `hlwid`). It makes
  sense for `mwiddeleg` to be a strict subset of `mwidlist` (as nothing unset
  in `mwidlist` can be expected to work), but there is no need to enforce this
  at the register level.
* `hwiddeleg`: this register determines the WIDs that VS-mode is allowed to
  assign to VU-mode, ie. those WIDs that can (or should) be set in `vslwid` when
  `V=1`. It makes sense for `hwiddeleg` to be a strict subset of `mwiddeleg`
  (as HS-mode can not successfully delegate WIDs that were not delegated to
  it).

[[runtimeDiscovery]]
==== Run-time discovery

From the ISA perspective, WID is simply an ID, it does not directly refer to
any resource of the core, so the number of WIDs that can be used and expressed
is constrained only by;

* the number of bits that can be signaled on outgoing transactions,
* the number of WID bits implemented in cache tags for any cache in the
  transaction path, and
* the number of bits implemented in registers that serve as WID bitmasks.

__Note: this should not be confused with the range of WIDs supported by any
given WID-aware target on the bus.__ Those targets may well use input WIDs as
indices into a finite array of resources, and those arrays might not even have
power-of-two geometry. I.e. each target supports a given set of WID inputs, and
how that set overlaps (or otherwise) with the set of WIDs that the ISA can
express is outside the scope of this document.

Here we are only concerned with the range of WIDs that can be expressed on
outgoing transactions, i.e. the range of WIDs that the core can assign to
privilege modes.

****
It is a software configuration responsibility to avoid the use of WIDs that the
ISA is able to express but that are outside the bounds supported by the targets
of outgoing transactions.
****

The ISA inherently limits the number of supported WIDs ("NWorlds" in WG terms)
to `XLEN`,footnote:[whether `XLEN` is 32, 64, or 128 depends on the RISC-V
hardware configuration] as there are XLEN-bit registers that serve as WID
bitmasks (`mwidlist`, `mwiddeleg`, `hwiddeleg`). However, an extension will
likely be proposed to extend the WID bitmasks, in which case this limit may be
overcome.

The ISA has another inherent upper limit (to the number of supported WIDs) of
2^16^, due to WID register fields being 16-bit wide.footnote:[Using a 16-bit
width for WID values is chosen to align with the IOPMP's use of 16-bit RRIDs.
See <<rridWid>> for more information.]

However, the actual ISA-supported range of WIDs is likely to be a considerably
smaller power of 2. (It may even be just 2.)

Software/firmware can discover the supported widths by writing a register with
all ones and reading the value back - the unsupported bits will read back as
zero.

* If the CSR is a WID-holding register (`mwid`, `mlwid`, `hlwid`, `slwid`,
  `vslwid`), the result will determine the supported WID-width in bits, the
  range of WIDs will therefore be from 0 to 2^WIDwidth^-1, inclusive.
* If the CSR is a WID-bitmask-holding register (`mwidlist`, `mwiddeleg`,
  `hwiddeleg`), the result will determine the range of WIDs itself, and this
  should be a power of 2.

The implementation must ensure that the two methods for determing the valid WID
range are consistent with one another, i.e. width(WIDBITMASK) == 2^width(WID)^

[[decisionLogic]]
=== Decision logic

The following two subsections describe how the World-ID extension determines
whether to accept or reject a load/store/fetch transaction. In all cases where
the decision is to reject the transaction, the fault type chosen for the
rejection will be derived from the transaction type:

* a load will trigger a "Load access fault"
* an instruction fetch will trigger an "Instruction access fault"
* a store will trigger a "Store/AMO access fault"

In the cases where the decision is to accept the transaction, this decision
logic also determines the WID value with which to tag the outgoing transaction.

==== Effective WID

The WID of each privilege mode is determined by the following registers;
....
          M-mode --> mwid
       HS/S-mode --> mlwid
         VS-mode --> hlwid
       HU/U-mode --> slwid
         VU-mode --> vslwid
....

* The "effective WID" is the WID of the current privilege mode.

==== Accept/reject

Please see <<hypervisorWGtree>> in <<hypervisor>> for a visual representation
of this decision logic.

* If the hart is in VU-mode (i.e. when U-mode and `V=1`), and if the effective
  WID is not set in `hwiddeleg`, reject transaction.
* If the hart is in VS-mode (i.e. when S-mode and `V=1`) or in any kind of
  U-mode, and if the effective WID is not set in `mwiddeleg`, reject
  transaction.
* If the hart is not in M-mode and the effective WID is not set in `mwidlist`,
  reject transaction.
* If the transaction is accepted, the effective WID is signaled on the outgoing
  transaction.

=== Power-on defaults

The working assumption is that power-on defaults should serve the purpose of
leaving the system without any effects or obligations associated with the
partitioning functionality. This is mostly achieved by having all settings come
up as "zero". External configuration (from a RoT) or early boot M-mode firmware
can choose to impose "non-zero" restrictions, so it makes sense for the
defaults to behave as though the system had no World-ID constraints in place.

==== External configuration disabled or optional

The one problem with the "zero method" is that the bitmask registers
`mwidlist`, `mwiddeleg`, and `hwiddeleg` control which WIDs (at different
privilege modes) are allowed to issue transactions, and so if those registers
are zero, the affected modes will be unable to issue an instruction fetch...

* If M-mode can be obliged to initialize World-ID settings before handing
  control to S-mode or U-mode, then M-mode's use of `mwid` suffices to
  bootstrap.
* Otherwise, to have system defaults that require no World-ID initialization,
  i.e. that function in all modes as though WG was not present, then
  `mwiddeleg` and `hwiddeleg` should default to `0x1`.

In <<worldRegisterMap>> below, we will assume the latter situation, such that the
power-on defaults allow the system to function "as though World-ID were
absent". If the implementation context has different requirements (such as an
obligatory external configuration via RoT), the power-on defaults can be
adapted.

[[worldRegisterMap]]
=== World-ID Register map

==== Summary

The following table contains the CSRs defined by this proposal.

[%header,cols="2,2,2,2,3"]
|===
| Register | Access | Proposed offset | Suggested default | Description

| `mwid` | RW for M until locked | ??? | `0x0` | WID for M-mode
| `mwidlist` | RW for M until locked | ??? | `0x1` | Set of allowable WIDs
| `mlwid` | RW for M | `0x390` | `0x0` | WID for (H)S-mode
| `mwiddeleg` | RW for M | `0x748` | `0x1` | Set of WIDs delegated to (H)S-mode
| `hlwid` | RW for (H)S | ??? | `0x0` | WID for VS-mode
| `hwiddeleg` | RW for (H)S | ??? | `0x1` | Set of WIDs delegated to VS-mode
| `slwid` | RW for S | `0x190` | `0x0` | WID for U-mode
| `vslwid` | RW for M | ??? | `0x0` | Virtual Supervisor mode Lower World Identifier
|===

The following sections provide more detail on each of these registers.

==== `mwid`: WID for M-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| L | `XLEN-1`
| Lock bit. Write 1 to lock register (as read-only) until next reset
| rsv | `[XLEN-2]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that M-mode operates in. Writable only up until L has been written 1.
Only Ceil(Log~2~(NWorlds)) LSBs are writable, others are read-only zero.
|===

This register and `mwidlist` become locked once the L bit is set, after which
the registers are read-only (and so `mwid` can't be unlocked) and writes are
silently dropped. The locking is only released when the block is reset. When
unlocked, all writes to these registers commit atomically.

Each CSR write to `mwid` updates both L and WID fields together. When writing 1
to `mwid.L`, the lock on all 3 registers takes effect after the write.

Only the lower Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining
are read-only zero.

==== `mwidlist`: Set of allowable WIDs

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| MASK | `[XLEN-1]:0`
| Bit-vector limiting the WIDs that may be used by this hart. LSB corresponds
to WID 0, `NWorlds` LSBs are used, others are read-only zero.
|===

This register is locked if and only if the `mwid` register is. The `mwidlist`
CSR ignores writes when locked by `mwid`. CSR writes to `mwidlist` and `mwid`
are ordered by the hardware in the same manner as writes to ePMP registers.
When necessary, software can enforce a specific ordering between a CSR write
and other instructions with an appropriate FENCE.

Only the lower NWorlds bits of MASK are implemented. The remaining are
read-only zero.

Note, `mwidlist` restrictions only apply to privilege modes below M-mode. I.e.
M-mode's use of the `mwid` WID is not constrained by `mwidlist`.

==== `mlwid`: WID for (H)S-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| rsv | `[XLEN-1]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that (H)S-mode operates in. Only Ceil(Log~2~(NWorlds)) LSBs are used,
others are read-only zero.
|===

This register does not lock so it remains writable to M-mode at all times.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

Writes to `mlwid` have the same ordering semantics as writes to the ePMP CSRs
with respect to when a write to `mlwid` takes effect.

==== `mwiddeleg`: Set of WIDs delegated to (H)S-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| MASK | `[XLEN-1]:0`
| Bit-vector limiting the WIDs that may be used with `hlwid` and `slwid`.
|===

This register does not lock so it remains writable to M-mode at all times.

Only the lower NWorlds bits of MASK are implemented. The remaining are
read-only zero.

==== `hlwid`: WID for VS-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| rsv | `[XLEN-1]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that VS-mode operates in. Only Ceil(Log~2~(NWorlds)) LSBs are used,
others are read-only zero.
|===

This register does not lock so it remains writable to M-mode at all times.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

Writes to `hlwid` have the same ordering semantics as writes to the ePMP CSRs
with respect to when a write to `hlwid` takes effect.

==== `hwiddeleg`: Set of WIDs delegated to VS-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| MASK | `[XLEN-1]:0`
| Bit-vector limiting the WIDs that may be used with `slwid` when `V=1` (i.e.
in VU-mode).
|===

This register does not lock so it remains writable to M-mode at all times.

Only the lower NWorlds bits of MASK are implemented. The remaining are
read-only zero.

==== `slwid`: WID for U-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| rsv | `[XLEN-1]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that U-mode operates in. Only Ceil(Log~2~(NWorlds)) LSBs are used, others
are read-only zero.
|===

This register does not lock so it remains writable to S-mode at all times.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

Writes to `slwid` have the same ordering semantics as writes to the ePMP CSRs
with respect to when a write to `slwid` takes effect.

==== `vslwid`: Virtual Supervisor mode Lower World Identifier

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| WID | `[XLEN-1]:0`
| This is the WID used in Virtual User mode when delegation is enabled. Only Ceil(Log~2~(NWorlds)) LSBs
are used, others are read-only zero.
|===

This CSR is the virtualization shadow register of the slwid register. In hypervisor extended S mode this register can be programmed to set the value to be used in virtual mode.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

