:imagesdir: ./images

[[isa]]
== "World-ID" ISA extension set

=== Preamble

The draft RISC-V "Worlds" specification, found at
https://github.com/riscv/riscv-worlds, proposes a sequence of incremental
extensions that progressively add CSR registers but do not add any new
instructions. We incorporate that specification with the following adaptations;

* We incorporate a proposal to extend the draft Worlds specification with
  support for the Hypervisor extension. The details of that proposal can be
  found at https://github.com/riscv/riscv-worlds/pull/19.
* We explicitly define the CSR formats and their power-on defaults.
* We assume that all extensions are implemented and enabled, so that
  implementations do not have to implement modal behavior to support different
  enablement combinations.
* We provide a table of "platform variables", whose existence are described in
  the draft Worlds specification but not summarily listed. An implementation
  may choose to correlate these variables to product-specific constants or
  even configuration options or system registers, as applicable.
* We identify the Worlds CSRs that should be exposed for external control.
* Due to the fact that the Worlds specification is still in draft status (as
  is the proposed enhancement to support the Hypervisor extension), we take a
  couple of measures to insulate this specification from conflicting with a
  future RISC-V specification;
** We prefix the CSR names with "mips". Note, to avoid the visual unpleasantness
   of renaming all mention of CSRs, we use the "mips" prefix only in the section
   listing and defining the CSRs, we leave the general documentation material
   without the "mips" prefix.
** We (re)define the CSR offsets to come from vendor-specific ranges, so that
   they won't conflict with any future public specification. These are chosen
   for use as-is by MIPS (who have reserved these offsets accordingly), but
   this might need further adjustment for use by other vendors.

=== Configuration handling

[[lockablePartitioning]]
==== Lockable partitioning registers

This category of CSRs should be exposed for external configuration control (by
an HSM, parent system, or other root of trust).

`mwid`, `mlwidlist`

* These registers are assumed to be set and locked to constrain the hart until
  it is next reset, and the behavior of the "run-time manipulable registers" is
  governed by these registers.
* Apart from the "L"ock bit in `mwid` (which is sticky to 1 and renders both
  registers read-only until the next reset), these registers are modifiable
  independently and no combination of values is illegal, _per se_.

[[runtimeManipulable]]
==== Run-time manipulable registers

These are the CSRs that are expected to be modified by M-mode and S-mode at
run-time, though many use-cases will use static/unchanging values for these
CSRs also. These CSRs are not lockable and are not exported for external
configuration, and so they are not considered part of the partitioning
configuration (rather, they work within the partitioning configuration).

`mlwid`, `mwiddeleg`, `hlwid`, `hwiddeleg`, `slwid`, `vslwid`

[[runtimeDiscovery]]
==== Run-time discovery

From the ISA perspective, WID is simply an ID, it does not directly refer to
any resource of the core, so the number of WIDs that can be used and expressed
is constrained only by;

* the number of bits that can be signaled on outgoing transactions,
* the number of WID bits implemented in cache tags for any cache in the
  transaction path, and
* the number of bits implemented in registers that serve as WID bitmasks.

__Note: this should not be confused with the range of WIDs supported by any
given WID-aware target on the bus.__ Those targets may well use input WIDs as
indices into a finite array of resources, and those arrays might not even have
power-of-two geometry. I.e. each target supports a given set of WID inputs, and
how that set overlaps (or otherwise) with the set of WIDs that the ISA can
express is outside the scope of this document.

Here we are only concerned with the range of WIDs that can be expressed on
outgoing transactions, i.e. the range of WIDs that the core can assign to
privilege modes.

****
It is a software configuration responsibility to avoid the use of WIDs that the
ISA is able to express but that are outside the bounds supported by the targets
of outgoing transactions.
****

The ISA inherently limits the number of supported WIDs ("NWorlds" in WG terms)
to `XLEN`,footnote:[whether `XLEN` is 32, 64, or 128 depends on the RISC-V
hardware configuration] as there are XLEN-bit registers that serve as WID
bitmasks (`mlwidlist`, `mwiddeleg`, `hwiddeleg`). However, an extension will
likely be proposed to extend the WID bitmasks, in which case this limit may be
overcome.

The ISA has another inherent upper limit (to the number of supported WIDs) of
2^16^, due to WID register fields being 16-bit wide.footnote:[Using a 16-bit
width for WID values is chosen to align with the IOPMP's use of 16-bit RRIDs.
See <<rridWid>> for more information.]

However, the actual ISA-supported range of WIDs is likely to be a considerably
smaller power of 2. (It may even be just 2.)

Software/firmware can discover the supported widths by writing a register with
all ones and reading the value back - the unsupported bits will read back as
zero.

* If the CSR is a WID-holding register (`mwid`, `mlwid`, `hlwid`, `slwid`,
  `vslwid`), the result will determine the supported WID-width in bits, the
  range of WIDs will therefore be from 0 to 2^WIDwidth^-1, inclusive.
* If the CSR is a WID-bitmask-holding register (`mlwidlist`, `mwiddeleg`,
  `hwiddeleg`), the result will determine the range of WIDs itself, and this
  should be a power of 2.

The implementation must ensure that the two methods for determing the valid WID
range are consistent with one another, i.e. width(WIDBITMASK) == 2^width(WID)^

==== Effective WID

The WID of each privilege mode is determined by the World-ID registers per the
following table, based on how many World-ID extensions are enabled (they are
enabled successively, from left-to-right). Note that the Smwiddeleg extension does
not add any WID registers and so presents the same characteristics as Smlwid.

[%header,cols="1,1,2,1,2"]
|===
^| Mode ^| Smwid  ^| Smlwid  ^| Sswid  ^| Shlwid (all enabled)
^| M    ^| `mwid` ^| `mwid`  ^| `mwid`  ^| `mwid`
^| HS/S ^| `mwid` ^| `mlwid` ^| `mlwid` ^| `mlwid`
^| VS   ^| `mwid` ^| `mlwid` ^| `mlwid` ^| `hlwid`
^| HU/U ^| `mwid` ^| `mlwid` ^| `slwid` ^| `slwid`
^| VU   ^| `mwid` ^| `mlwid` ^| `slwid` ^| `vslwid`
|===

* The "effective WID" is the WID of the current privilege mode.
* This proposal suggests that all the Worlds extensions be implemented and
  enabled, implying that the right-most column will always apply.

=== Power-on defaults

The working assumption is that power-on defaults should serve the purpose of
leaving the system without any effects or obligations associated with the
partitioning functionality. This is mostly achieved by having all settings come
up as "zero". External configuration (from a RoT) or early boot M-mode firmware
can choose to impose "non-zero" restrictions, so it makes sense for the
defaults to behave as though the system had no World-ID constraints in place.

==== External configuration disabled or optional

The one problem with the "zero method" is that the bitmask registers
`mlwidlist`, `mwiddeleg`, and `hwiddeleg` control which WIDs (at different
privilege modes) are allowed to issue transactions, and so if those registers
are zero, the affected modes will be unable to issue an instruction fetch...

* If M-mode can be obliged to initialize World-ID settings before handing
  control to S-mode or U-mode, then M-mode's use of `mwid` suffices to
  bootstrap.
* Otherwise, to have system defaults that require no World-ID initialization,
  i.e. that function in all modes as though WG was not present, then
  `mwiddeleg` and `hwiddeleg` should default to `0x1`.

In <<worldRegisterMap>> below, we will assume the latter situation, such that the
power-on defaults allow the system to function "as though World-ID were
absent". If the implementation context has different requirements (such as an
obligatory external configuration via RoT), the power-on defaults can be
adapted.

[[worldRegisterMap]]
=== World-ID Register map

==== Summary

[%header,cols="2,2,2,2,3"]
|===
| Register | Access | Proposed offset | Suggested default | Description
| `mipsmwid` | RW for M until locked | `0x7f1` | `0x0` | WID for M-mode
| `mipsmlwid` | RW for M | `0x7f4` | `0x0` | WID for (H)S-mode
| `mipsmlwidlist` | RW for M until locked | `0x7f2` | `0x1` | Set of allowable WIDs
| `mipsmwiddeleg` | RW for M | `0x7f5` | `0x1` | Set of WIDs delegated to (H)S-mode
| `mipshlwid` | RW for (H)S | ??? | `0x0` | WID for VS-mode
| `mipshwiddeleg` | RW for (H)S | ??? | `0x1` | Set of WIDs delegated to VS-mode
| `mipsslwid` | RW for S | `0x9d4` | `0x0` | WID for U-mode
| `mipsvslwid` | RW for M | ??? | `0x0` | Virtual Supervisor mode Lower World Identifier
|===

The following sections provide more detail on each of these registers.

==== `mipsmwid`: WID for M-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| L | `XLEN-1`
| Lock bit. Write 1 to lock register (as read-only) until next reset
| rsv | `[XLEN-2]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that M-mode operates in. Writable only up until L has been written 1.
Only Ceil(Log~2~(NWorlds)) LSBs are writable, others are read-only zero.
|===

This register and `mlwidlist` become locked once the L bit is set, after which
the registers are read-only (and so `mwid` can't be unlocked) and writes are
silently dropped. The locking is only released when the block is reset. When
unlocked, all writes to these registers commit atomically.

Each CSR write to `mwid` updates both L and WID fields together. When writing 1
to `mwid.L`, the lock on all 3 registers takes effect after the write.

Only the lower Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining
are read-only zero.

==== `mipsmlwid`: WID for (H)S-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| rsv | `[XLEN-1]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that (H)S-mode operates in. Only Ceil(Log~2~(NWorlds)) LSBs are used,
others are read-only zero.
|===

This register does not lock so it remains writable to M-mode at all times.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

Writes to `mlwid` have the same ordering semantics as writes to the ePMP CSRs
with respect to when a write to `mlwid` takes effect.

==== `mipsmlwidlist`: Set of allowable WIDs

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| MASK | `[XLEN-1]:0`
| Bit-vector limiting the WIDs that may be used by this hart. LSB corresponds
to WID 0, `NWorlds` LSBs are used, others are read-only zero.
|===

This register is locked if and only if the `mwid` register is. The `mlwidlist`
CSR ignores writes when locked by `mwid`. CSR writes to `mlwidlist` and `mwid`
are ordered by the hardware in the same manner as writes to ePMP registers.
When necessary, software can enforce a specific ordering between a CSR write
and other instructions with an appropriate FENCE.

Only the lower NWorlds bits of MASK are implemented. The remaining are
read-only zero.

Note, `mlwidlist` restrictions only apply to privilege modes below M-mode. I.e.
M-mode's use of the `mwid` WID is not constrained by `mlwidlist`.

==== `mipsmwiddeleg`: Set of WIDs delegated to (H)S-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| MASK | `[XLEN-1]:0`
| Bit-vector limiting the WIDs that may be used with `hlwid` and `slwid`.
|===

This register does not lock so it remains writable to M-mode at all times.

Only the lower NWorlds bits of MASK are implemented. The remaining are
read-only zero.

==== `mipshlwid`: WID for VS-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| rsv | `[XLEN-1]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that VS-mode operates in. Only Ceil(Log~2~(NWorlds)) LSBs are used,
others are read-only zero.
|===

This register does not lock so it remains writable to M-mode at all times.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

Writes to `hlwid` have the same ordering semantics as writes to the ePMP CSRs
with respect to when a write to `hlwid` takes effect.

==== `mipshwiddeleg`: Set of WIDs delegated to VS-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| MASK | `[XLEN-1]:0`
| Bit-vector limiting the WIDs that may be used with `slwid` when `V=1` (i.e.
in VU-mode).
|===

This register does not lock so it remains writable to M-mode at all times.

Only the lower NWorlds bits of MASK are implemented. The remaining are
read-only zero.

==== `mipsslwid`: WID for U-mode

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| rsv | `[XLEN-1]:16` | Reserved, wired to zero.
| WID | `15:0`
| WID that U-mode operates in. Only Ceil(Log~2~(NWorlds)) LSBs are used, others
are read-only zero.
|===

This register does not lock so it remains writable to S-mode at all times.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

Writes to `slwid` have the same ordering semantics as writes to the ePMP CSRs
with respect to when a write to `slwid` takes effect.

==== `mipsvslwid`: Virtual Supervisor mode Lower World Identifier

[%header,cols="1,1,5"]
|===
| Name | Bits | Description
| WID | `[XLEN-1]:0`
| This is the WID used in Virtual User mode when delegation is enabled. Only Ceil(Log~2~(NWorlds)) LSBs
are used, others are read-only zero.
|===

This CSR is the virtualization shadow register of the slwid register. In hypervisor extended S mode this register can be programmed to set the value to be used in virtual mode.

Only Ceil(Log~2~(NWorlds)) bits of WID are implemented. The remaining are
read-only zero.

