:imagesdir: ./images

[[sqISA]]
== "Security Qualifiers" ISA extension

=== Preamble

* The "World-ID" and "Security Levels" ISA extension sets are augmented;
** Definition of the Security Qualifier type, that the implementation is
   required to maintain for all (hart-accessible) address ranges. See <<sq>>.
** Enhanced ePMP checking, to compare the effective Security Level (of the
   current privilege level's WID) against the Security Qualifier(s) for the
   target address range(s). See <<sqPMP>>.
* Guidance is provided regarding M-mode changing its own Security Level.
  (See "Changing Security Level" below in <<changingSecurityLevel>>.)

[[sq]]
=== Security Qualifier

When access to a resource is protected by a Security Qualifier, the qualifier
has three fields that are used to treat potential transactions;

* Threshold: this expresses the lowest Security Level (i.e. the highest SL
  _value_) that is allowed to access the resource.
* Treatment: if the access is permitted by the Threshold field, should the
  outgoing transaction be signalled with the Security Level of the requester or
  should all transactions accepted by this qualifier carry a common Security
  Level? The "Treatment" field is a Boolean answer to this question.
* Value: if the "Treatment" field indicates that a common Security Level should
  be used for outgoing transactions to this resource, "Value" is that Security
  Level. "Value" cannot be superior (i.e. of a lower SL _value_) to
  "Threshold", in order to block privilege-escalation.

The use of Treatment/Value is to handle cases where a downstream checker will be
encountered by the outgoing transaction, and where all hart accesses to that
resource (that aren't rejected) should signal at a common Security Level.

=== Instruction fetch and table walk

It is dangerous to trust instructions or page table entries that are fetched
from memory that is accessible to inferior (higher-valued) security levels. So,
for transactions that are instruction fetches or loads for MMU page tables, the
comparison between the effective Security Level and the Security Qualifier's
Threshold field becomes one of "equality" (rather than "superior or equal to"
as is normally the case).

=== Decision logic

The following subsections show the additional constraints for determining
whether to accept or reject a load/store/fetch transaction. See
<<decisionLogic>> for more information on how rejections are handled.

[[sqPMP]]
==== Security Qualifier accept/reject

Per the description of Security Qualifiers above, the hart (probably in the
ePMP) uses the following additional constraint logic to determine the fate of a
potential load/store/fetch transaction;

* If the Effective Security Level is inferior to the Security Qualifier's
  "Threshold" field (i.e. higher-valued), reject the transaction.
* If the transaction is an instruction fetch or MMU page-table load, and the
  Effective Security Level is different to the Security Qualifier's "Threshold"
  field, reject the transaction.
* The Security Qualifier's "Treatment" field indicates the Security Level that
  the outgoing transaction should be signalled with; either the Effective
  Security Level or the Security Qualifier's "Value" field.

[[changingSecurityLevel]]
=== Changing Security Level

If the intention is for M-mode to modify the Security Level of its own WID,
there is a subtlety to note about modifications to the `mwid` and
`mwidseclistX` CSR registers.

Consider, if the current `mwid` and `mwidseclistX` CSR values imply that the
Security Level of M-mode is `A`, then any M-mode instruction fetches must
necessarily be going to memory whose Security Qualifier has a "Threshold" value
of `A`. It would follow that M-mode can never safely cause its current Security
Level to change (to anything other than `A`) by issuing writes to `mwid` or
`mwidseclistX`, because the write that triggers the change of Security Level
will be followed immediately by an instruction fetch fault - because the next
instruction fetch is to the same type of memory as before, but the new Security
Level now expects the memory to have a different Security Qualifier.

Now, if `mwid` is configured externally, before the harts are executing, this
problem doesn't arise. Likewise, if M-mode doesn't need to support running in
anything other than the maximum Security Level (zero, the default), no problem.
This issue only arises if M-mode is performing the Security Level change within
the hart itself through write operations.

The recommended solution, for any platform/implementation that needs to handle
this case, is to "embrace the fault". Namely, in preparation for changing
M-mode's Security Level, the trap vectors will necessarily need to be changed
to point to the type of memory that the new Security Level will expect, and so
once M-mode makes the write that triggers the change of Security Level, the
following instruction fetch will fault into an M-mode trap handler that is
running out of the type of memory that the new Security Level expects. In this
way, control is passed from the previously-required memory type to the
newly-required memory type.

