:imagesdir: ./images

[[sqepmpISA]]
== "ePMP Security Qualifiers" ISA extension

=== Preamble

* The "World-ID", "Security Levels", and "Security Qualifiers" ISA extensions
  are augmented;
** Definition of the `pmpsqX` registers, that allow Security Qualifiers to be
   associated with each ePMP entry

Recall from the "Security Qualifiers" ISA extension, that the implementation is
responsible for maintaining the Security Qualifiers for the hart-accessible
physical address space, so that access control can be performed by comparing
the hart's effective Security Level against the target's Security Qualifier. It
is left undefined (a) how the implementation should do this, and (b) what
configuration interface would be used to provision it.

One possibility is to treat the Security Qualifier as a new PMA (Physical
Memory Attribute). The treatment of PMAs is also left undefined and
implementation-specific, but as that is presumably a solved problem for
existing implementations, extending it for Security Qualifiers would benefit
from the existing framework.

Another possibility is to store the Security Qualifiers in ePMP (and eIOPMP)
entries, given that the hart will already be consulting ePMP for access control
over outgoing transactions, and so it is a low-effort adaptation to retrieve
the Security Qualifier from whatever ePMP entry the transaction matches
against. This extension provides exactly that functionality.

=== `pmpsqX` registers

For each PMP entry X, the corresponding `pmpsqX` register encodes the Security
Qualifier that is associated with X's address range. A Security Qualifier
consists of two Security Levels ("Threshold" and "Value") plus 1 Boolean
("Treatment"), so if the number of bits required to encode a Security Level is
`N`, then the number of bits required to encode a Security Qualifier is `2N+1`.

The `pmpsqX` registers will be densely packed into `XLEN` sized CSRs, in
sufficient number to match the ePMP entry array size.

Register details are TBD.

